title: Scalando
author: "Ettore Delprino"
email: edelprino@gmail.com
description: Le ultime news dal mondo dell'arrampicata
# description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://scalando.net" # the base hostname & protocol for your site

permalink: /:year/:title/
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock

